
services:
  node_app:
    build:
      context: .
    volumes:
      - ./:/app 
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npm run dev

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:      




    
    