# Login request
POST http://localhost:3000/addUser
Content-Type: application/json

{
    "email": "g",
    "password":"g"
}
###

GET http://localhost:3000/getUser/1
Content-Type: application/json





