# Login request
POST http://localhost:3000/turnOnLights/5
Content-Type: application/json


###
POST http://localhost:3000/turnOffLights/1
Content-Type: application/json


###
GET http://localhost:3000/getUser/1
Content-Type: application/json





